# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\texst\Scientific-Article-Management

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\texst\Scientific-Article-Management

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	"C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	"C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\texst\Scientific-Article-Management\CMakeFiles D:\texst\Scientific-Article-Management\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\texst\Scientific-Article-Management\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named LoginForm

# Build rule for target.
LoginForm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 LoginForm
.PHONY : LoginForm

# fast build rule for target.
LoginForm/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/build
.PHONY : LoginForm/fast

#=============================================================================
# Target rules for targets named LoginForm_autogen_timestamp_deps

# Build rule for target.
LoginForm_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 LoginForm_autogen_timestamp_deps
.PHONY : LoginForm_autogen_timestamp_deps

# fast build rule for target.
LoginForm_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm_autogen_timestamp_deps.dir\build.make CMakeFiles/LoginForm_autogen_timestamp_deps.dir/build
.PHONY : LoginForm_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named LoginForm_autogen

# Build rule for target.
LoginForm_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 LoginForm_autogen
.PHONY : LoginForm_autogen

# fast build rule for target.
LoginForm_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm_autogen.dir\build.make CMakeFiles/LoginForm_autogen.dir/build
.PHONY : LoginForm_autogen/fast

LoginForm_autogen/mocs_compilation.obj: LoginForm_autogen/mocs_compilation.cpp.obj
.PHONY : LoginForm_autogen/mocs_compilation.obj

# target to build an object file
LoginForm_autogen/mocs_compilation.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/LoginForm_autogen/mocs_compilation.cpp.obj
.PHONY : LoginForm_autogen/mocs_compilation.cpp.obj

LoginForm_autogen/mocs_compilation.i: LoginForm_autogen/mocs_compilation.cpp.i
.PHONY : LoginForm_autogen/mocs_compilation.i

# target to preprocess a source file
LoginForm_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/LoginForm_autogen/mocs_compilation.cpp.i
.PHONY : LoginForm_autogen/mocs_compilation.cpp.i

LoginForm_autogen/mocs_compilation.s: LoginForm_autogen/mocs_compilation.cpp.s
.PHONY : LoginForm_autogen/mocs_compilation.s

# target to generate assembly for a file
LoginForm_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/LoginForm_autogen/mocs_compilation.cpp.s
.PHONY : LoginForm_autogen/mocs_compilation.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mainwindow.obj: src/mainwindow.cpp.obj
.PHONY : src/mainwindow.obj

# target to build an object file
src/mainwindow.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/mainwindow.cpp.obj
.PHONY : src/mainwindow.cpp.obj

src/mainwindow.i: src/mainwindow.cpp.i
.PHONY : src/mainwindow.i

# target to preprocess a source file
src/mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/mainwindow.cpp.i
.PHONY : src/mainwindow.cpp.i

src/mainwindow.s: src/mainwindow.cpp.s
.PHONY : src/mainwindow.s

# target to generate assembly for a file
src/mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/mainwindow.cpp.s
.PHONY : src/mainwindow.cpp.s

src/models/articles/Article.obj: src/models/articles/Article.cpp.obj
.PHONY : src/models/articles/Article.obj

# target to build an object file
src/models/articles/Article.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/models/articles/Article.cpp.obj
.PHONY : src/models/articles/Article.cpp.obj

src/models/articles/Article.i: src/models/articles/Article.cpp.i
.PHONY : src/models/articles/Article.i

# target to preprocess a source file
src/models/articles/Article.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/models/articles/Article.cpp.i
.PHONY : src/models/articles/Article.cpp.i

src/models/articles/Article.s: src/models/articles/Article.cpp.s
.PHONY : src/models/articles/Article.s

# target to generate assembly for a file
src/models/articles/Article.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/models/articles/Article.cpp.s
.PHONY : src/models/articles/Article.cpp.s

src/models/articles/Author.obj: src/models/articles/Author.cpp.obj
.PHONY : src/models/articles/Author.obj

# target to build an object file
src/models/articles/Author.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/models/articles/Author.cpp.obj
.PHONY : src/models/articles/Author.cpp.obj

src/models/articles/Author.i: src/models/articles/Author.cpp.i
.PHONY : src/models/articles/Author.i

# target to preprocess a source file
src/models/articles/Author.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/models/articles/Author.cpp.i
.PHONY : src/models/articles/Author.cpp.i

src/models/articles/Author.s: src/models/articles/Author.cpp.s
.PHONY : src/models/articles/Author.s

# target to generate assembly for a file
src/models/articles/Author.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/models/articles/Author.cpp.s
.PHONY : src/models/articles/Author.cpp.s

src/models/articles/CONFERENCE_Article.obj: src/models/articles/CONFERENCE_Article.cpp.obj
.PHONY : src/models/articles/CONFERENCE_Article.obj

# target to build an object file
src/models/articles/CONFERENCE_Article.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/models/articles/CONFERENCE_Article.cpp.obj
.PHONY : src/models/articles/CONFERENCE_Article.cpp.obj

src/models/articles/CONFERENCE_Article.i: src/models/articles/CONFERENCE_Article.cpp.i
.PHONY : src/models/articles/CONFERENCE_Article.i

# target to preprocess a source file
src/models/articles/CONFERENCE_Article.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/models/articles/CONFERENCE_Article.cpp.i
.PHONY : src/models/articles/CONFERENCE_Article.cpp.i

src/models/articles/CONFERENCE_Article.s: src/models/articles/CONFERENCE_Article.cpp.s
.PHONY : src/models/articles/CONFERENCE_Article.s

# target to generate assembly for a file
src/models/articles/CONFERENCE_Article.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/models/articles/CONFERENCE_Article.cpp.s
.PHONY : src/models/articles/CONFERENCE_Article.cpp.s

src/models/articles/OTHER_Article.obj: src/models/articles/OTHER_Article.cpp.obj
.PHONY : src/models/articles/OTHER_Article.obj

# target to build an object file
src/models/articles/OTHER_Article.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/models/articles/OTHER_Article.cpp.obj
.PHONY : src/models/articles/OTHER_Article.cpp.obj

src/models/articles/OTHER_Article.i: src/models/articles/OTHER_Article.cpp.i
.PHONY : src/models/articles/OTHER_Article.i

# target to preprocess a source file
src/models/articles/OTHER_Article.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/models/articles/OTHER_Article.cpp.i
.PHONY : src/models/articles/OTHER_Article.cpp.i

src/models/articles/OTHER_Article.s: src/models/articles/OTHER_Article.cpp.s
.PHONY : src/models/articles/OTHER_Article.s

# target to generate assembly for a file
src/models/articles/OTHER_Article.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/models/articles/OTHER_Article.cpp.s
.PHONY : src/models/articles/OTHER_Article.cpp.s

src/models/articles/SCIE_Article.obj: src/models/articles/SCIE_Article.cpp.obj
.PHONY : src/models/articles/SCIE_Article.obj

# target to build an object file
src/models/articles/SCIE_Article.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/models/articles/SCIE_Article.cpp.obj
.PHONY : src/models/articles/SCIE_Article.cpp.obj

src/models/articles/SCIE_Article.i: src/models/articles/SCIE_Article.cpp.i
.PHONY : src/models/articles/SCIE_Article.i

# target to preprocess a source file
src/models/articles/SCIE_Article.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/models/articles/SCIE_Article.cpp.i
.PHONY : src/models/articles/SCIE_Article.cpp.i

src/models/articles/SCIE_Article.s: src/models/articles/SCIE_Article.cpp.s
.PHONY : src/models/articles/SCIE_Article.s

# target to generate assembly for a file
src/models/articles/SCIE_Article.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/models/articles/SCIE_Article.cpp.s
.PHONY : src/models/articles/SCIE_Article.cpp.s

src/models/articles/SCOPUS_Article.obj: src/models/articles/SCOPUS_Article.cpp.obj
.PHONY : src/models/articles/SCOPUS_Article.obj

# target to build an object file
src/models/articles/SCOPUS_Article.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/models/articles/SCOPUS_Article.cpp.obj
.PHONY : src/models/articles/SCOPUS_Article.cpp.obj

src/models/articles/SCOPUS_Article.i: src/models/articles/SCOPUS_Article.cpp.i
.PHONY : src/models/articles/SCOPUS_Article.i

# target to preprocess a source file
src/models/articles/SCOPUS_Article.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/models/articles/SCOPUS_Article.cpp.i
.PHONY : src/models/articles/SCOPUS_Article.cpp.i

src/models/articles/SCOPUS_Article.s: src/models/articles/SCOPUS_Article.cpp.s
.PHONY : src/models/articles/SCOPUS_Article.s

# target to generate assembly for a file
src/models/articles/SCOPUS_Article.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/models/articles/SCOPUS_Article.cpp.s
.PHONY : src/models/articles/SCOPUS_Article.cpp.s

src/models/users/Admin.obj: src/models/users/Admin.cpp.obj
.PHONY : src/models/users/Admin.obj

# target to build an object file
src/models/users/Admin.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/models/users/Admin.cpp.obj
.PHONY : src/models/users/Admin.cpp.obj

src/models/users/Admin.i: src/models/users/Admin.cpp.i
.PHONY : src/models/users/Admin.i

# target to preprocess a source file
src/models/users/Admin.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/models/users/Admin.cpp.i
.PHONY : src/models/users/Admin.cpp.i

src/models/users/Admin.s: src/models/users/Admin.cpp.s
.PHONY : src/models/users/Admin.s

# target to generate assembly for a file
src/models/users/Admin.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/models/users/Admin.cpp.s
.PHONY : src/models/users/Admin.cpp.s

src/models/users/Reviewer.obj: src/models/users/Reviewer.cpp.obj
.PHONY : src/models/users/Reviewer.obj

# target to build an object file
src/models/users/Reviewer.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/models/users/Reviewer.cpp.obj
.PHONY : src/models/users/Reviewer.cpp.obj

src/models/users/Reviewer.i: src/models/users/Reviewer.cpp.i
.PHONY : src/models/users/Reviewer.i

# target to preprocess a source file
src/models/users/Reviewer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/models/users/Reviewer.cpp.i
.PHONY : src/models/users/Reviewer.cpp.i

src/models/users/Reviewer.s: src/models/users/Reviewer.cpp.s
.PHONY : src/models/users/Reviewer.s

# target to generate assembly for a file
src/models/users/Reviewer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/models/users/Reviewer.cpp.s
.PHONY : src/models/users/Reviewer.cpp.s

src/models/users/User.obj: src/models/users/User.cpp.obj
.PHONY : src/models/users/User.obj

# target to build an object file
src/models/users/User.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/models/users/User.cpp.obj
.PHONY : src/models/users/User.cpp.obj

src/models/users/User.i: src/models/users/User.cpp.i
.PHONY : src/models/users/User.i

# target to preprocess a source file
src/models/users/User.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/models/users/User.cpp.i
.PHONY : src/models/users/User.cpp.i

src/models/users/User.s: src/models/users/User.cpp.s
.PHONY : src/models/users/User.s

# target to generate assembly for a file
src/models/users/User.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/models/users/User.cpp.s
.PHONY : src/models/users/User.cpp.s

src/repositories/ArticleRepo.obj: src/repositories/ArticleRepo.cpp.obj
.PHONY : src/repositories/ArticleRepo.obj

# target to build an object file
src/repositories/ArticleRepo.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/repositories/ArticleRepo.cpp.obj
.PHONY : src/repositories/ArticleRepo.cpp.obj

src/repositories/ArticleRepo.i: src/repositories/ArticleRepo.cpp.i
.PHONY : src/repositories/ArticleRepo.i

# target to preprocess a source file
src/repositories/ArticleRepo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/repositories/ArticleRepo.cpp.i
.PHONY : src/repositories/ArticleRepo.cpp.i

src/repositories/ArticleRepo.s: src/repositories/ArticleRepo.cpp.s
.PHONY : src/repositories/ArticleRepo.s

# target to generate assembly for a file
src/repositories/ArticleRepo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/repositories/ArticleRepo.cpp.s
.PHONY : src/repositories/ArticleRepo.cpp.s

src/repositories/AuthorArticleRepo.obj: src/repositories/AuthorArticleRepo.cpp.obj
.PHONY : src/repositories/AuthorArticleRepo.obj

# target to build an object file
src/repositories/AuthorArticleRepo.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/repositories/AuthorArticleRepo.cpp.obj
.PHONY : src/repositories/AuthorArticleRepo.cpp.obj

src/repositories/AuthorArticleRepo.i: src/repositories/AuthorArticleRepo.cpp.i
.PHONY : src/repositories/AuthorArticleRepo.i

# target to preprocess a source file
src/repositories/AuthorArticleRepo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/repositories/AuthorArticleRepo.cpp.i
.PHONY : src/repositories/AuthorArticleRepo.cpp.i

src/repositories/AuthorArticleRepo.s: src/repositories/AuthorArticleRepo.cpp.s
.PHONY : src/repositories/AuthorArticleRepo.s

# target to generate assembly for a file
src/repositories/AuthorArticleRepo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/repositories/AuthorArticleRepo.cpp.s
.PHONY : src/repositories/AuthorArticleRepo.cpp.s

src/repositories/AuthorRepo.obj: src/repositories/AuthorRepo.cpp.obj
.PHONY : src/repositories/AuthorRepo.obj

# target to build an object file
src/repositories/AuthorRepo.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/repositories/AuthorRepo.cpp.obj
.PHONY : src/repositories/AuthorRepo.cpp.obj

src/repositories/AuthorRepo.i: src/repositories/AuthorRepo.cpp.i
.PHONY : src/repositories/AuthorRepo.i

# target to preprocess a source file
src/repositories/AuthorRepo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/repositories/AuthorRepo.cpp.i
.PHONY : src/repositories/AuthorRepo.cpp.i

src/repositories/AuthorRepo.s: src/repositories/AuthorRepo.cpp.s
.PHONY : src/repositories/AuthorRepo.s

# target to generate assembly for a file
src/repositories/AuthorRepo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/repositories/AuthorRepo.cpp.s
.PHONY : src/repositories/AuthorRepo.cpp.s

src/repositories/RepositoryManager.obj: src/repositories/RepositoryManager.cpp.obj
.PHONY : src/repositories/RepositoryManager.obj

# target to build an object file
src/repositories/RepositoryManager.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/repositories/RepositoryManager.cpp.obj
.PHONY : src/repositories/RepositoryManager.cpp.obj

src/repositories/RepositoryManager.i: src/repositories/RepositoryManager.cpp.i
.PHONY : src/repositories/RepositoryManager.i

# target to preprocess a source file
src/repositories/RepositoryManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/repositories/RepositoryManager.cpp.i
.PHONY : src/repositories/RepositoryManager.cpp.i

src/repositories/RepositoryManager.s: src/repositories/RepositoryManager.cpp.s
.PHONY : src/repositories/RepositoryManager.s

# target to generate assembly for a file
src/repositories/RepositoryManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/repositories/RepositoryManager.cpp.s
.PHONY : src/repositories/RepositoryManager.cpp.s

src/services/ArticleService.obj: src/services/ArticleService.cpp.obj
.PHONY : src/services/ArticleService.obj

# target to build an object file
src/services/ArticleService.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/services/ArticleService.cpp.obj
.PHONY : src/services/ArticleService.cpp.obj

src/services/ArticleService.i: src/services/ArticleService.cpp.i
.PHONY : src/services/ArticleService.i

# target to preprocess a source file
src/services/ArticleService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/services/ArticleService.cpp.i
.PHONY : src/services/ArticleService.cpp.i

src/services/ArticleService.s: src/services/ArticleService.cpp.s
.PHONY : src/services/ArticleService.s

# target to generate assembly for a file
src/services/ArticleService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/services/ArticleService.cpp.s
.PHONY : src/services/ArticleService.cpp.s

src/services/DataManipulation.obj: src/services/DataManipulation.cpp.obj
.PHONY : src/services/DataManipulation.obj

# target to build an object file
src/services/DataManipulation.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/services/DataManipulation.cpp.obj
.PHONY : src/services/DataManipulation.cpp.obj

src/services/DataManipulation.i: src/services/DataManipulation.cpp.i
.PHONY : src/services/DataManipulation.i

# target to preprocess a source file
src/services/DataManipulation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/services/DataManipulation.cpp.i
.PHONY : src/services/DataManipulation.cpp.i

src/services/DataManipulation.s: src/services/DataManipulation.cpp.s
.PHONY : src/services/DataManipulation.s

# target to generate assembly for a file
src/services/DataManipulation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/services/DataManipulation.cpp.s
.PHONY : src/services/DataManipulation.cpp.s

src/utilities/MenuUtilities.obj: src/utilities/MenuUtilities.cpp.obj
.PHONY : src/utilities/MenuUtilities.obj

# target to build an object file
src/utilities/MenuUtilities.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/utilities/MenuUtilities.cpp.obj
.PHONY : src/utilities/MenuUtilities.cpp.obj

src/utilities/MenuUtilities.i: src/utilities/MenuUtilities.cpp.i
.PHONY : src/utilities/MenuUtilities.i

# target to preprocess a source file
src/utilities/MenuUtilities.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/utilities/MenuUtilities.cpp.i
.PHONY : src/utilities/MenuUtilities.cpp.i

src/utilities/MenuUtilities.s: src/utilities/MenuUtilities.cpp.s
.PHONY : src/utilities/MenuUtilities.s

# target to generate assembly for a file
src/utilities/MenuUtilities.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/utilities/MenuUtilities.cpp.s
.PHONY : src/utilities/MenuUtilities.cpp.s

src/utilities/Statistics.obj: src/utilities/Statistics.cpp.obj
.PHONY : src/utilities/Statistics.obj

# target to build an object file
src/utilities/Statistics.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/utilities/Statistics.cpp.obj
.PHONY : src/utilities/Statistics.cpp.obj

src/utilities/Statistics.i: src/utilities/Statistics.cpp.i
.PHONY : src/utilities/Statistics.i

# target to preprocess a source file
src/utilities/Statistics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/utilities/Statistics.cpp.i
.PHONY : src/utilities/Statistics.cpp.i

src/utilities/Statistics.s: src/utilities/Statistics.cpp.s
.PHONY : src/utilities/Statistics.s

# target to generate assembly for a file
src/utilities/Statistics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/utilities/Statistics.cpp.s
.PHONY : src/utilities/Statistics.cpp.s

src/utilities/UUID_Generator.obj: src/utilities/UUID_Generator.cpp.obj
.PHONY : src/utilities/UUID_Generator.obj

# target to build an object file
src/utilities/UUID_Generator.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/utilities/UUID_Generator.cpp.obj
.PHONY : src/utilities/UUID_Generator.cpp.obj

src/utilities/UUID_Generator.i: src/utilities/UUID_Generator.cpp.i
.PHONY : src/utilities/UUID_Generator.i

# target to preprocess a source file
src/utilities/UUID_Generator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/utilities/UUID_Generator.cpp.i
.PHONY : src/utilities/UUID_Generator.cpp.i

src/utilities/UUID_Generator.s: src/utilities/UUID_Generator.cpp.s
.PHONY : src/utilities/UUID_Generator.s

# target to generate assembly for a file
src/utilities/UUID_Generator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LoginForm.dir\build.make CMakeFiles/LoginForm.dir/src/utilities/UUID_Generator.cpp.s
.PHONY : src/utilities/UUID_Generator.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... install
	@echo ... install/local
	@echo ... install/strip
	@echo ... list_install_components
	@echo ... rebuild_cache
	@echo ... LoginForm_autogen
	@echo ... LoginForm_autogen_timestamp_deps
	@echo ... LoginForm
	@echo ... LoginForm_autogen/mocs_compilation.obj
	@echo ... LoginForm_autogen/mocs_compilation.i
	@echo ... LoginForm_autogen/mocs_compilation.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
	@echo ... src/mainwindow.obj
	@echo ... src/mainwindow.i
	@echo ... src/mainwindow.s
	@echo ... src/models/articles/Article.obj
	@echo ... src/models/articles/Article.i
	@echo ... src/models/articles/Article.s
	@echo ... src/models/articles/Author.obj
	@echo ... src/models/articles/Author.i
	@echo ... src/models/articles/Author.s
	@echo ... src/models/articles/CONFERENCE_Article.obj
	@echo ... src/models/articles/CONFERENCE_Article.i
	@echo ... src/models/articles/CONFERENCE_Article.s
	@echo ... src/models/articles/OTHER_Article.obj
	@echo ... src/models/articles/OTHER_Article.i
	@echo ... src/models/articles/OTHER_Article.s
	@echo ... src/models/articles/SCIE_Article.obj
	@echo ... src/models/articles/SCIE_Article.i
	@echo ... src/models/articles/SCIE_Article.s
	@echo ... src/models/articles/SCOPUS_Article.obj
	@echo ... src/models/articles/SCOPUS_Article.i
	@echo ... src/models/articles/SCOPUS_Article.s
	@echo ... src/models/users/Admin.obj
	@echo ... src/models/users/Admin.i
	@echo ... src/models/users/Admin.s
	@echo ... src/models/users/Reviewer.obj
	@echo ... src/models/users/Reviewer.i
	@echo ... src/models/users/Reviewer.s
	@echo ... src/models/users/User.obj
	@echo ... src/models/users/User.i
	@echo ... src/models/users/User.s
	@echo ... src/repositories/ArticleRepo.obj
	@echo ... src/repositories/ArticleRepo.i
	@echo ... src/repositories/ArticleRepo.s
	@echo ... src/repositories/AuthorArticleRepo.obj
	@echo ... src/repositories/AuthorArticleRepo.i
	@echo ... src/repositories/AuthorArticleRepo.s
	@echo ... src/repositories/AuthorRepo.obj
	@echo ... src/repositories/AuthorRepo.i
	@echo ... src/repositories/AuthorRepo.s
	@echo ... src/repositories/RepositoryManager.obj
	@echo ... src/repositories/RepositoryManager.i
	@echo ... src/repositories/RepositoryManager.s
	@echo ... src/services/ArticleService.obj
	@echo ... src/services/ArticleService.i
	@echo ... src/services/ArticleService.s
	@echo ... src/services/DataManipulation.obj
	@echo ... src/services/DataManipulation.i
	@echo ... src/services/DataManipulation.s
	@echo ... src/utilities/MenuUtilities.obj
	@echo ... src/utilities/MenuUtilities.i
	@echo ... src/utilities/MenuUtilities.s
	@echo ... src/utilities/Statistics.obj
	@echo ... src/utilities/Statistics.i
	@echo ... src/utilities/Statistics.s
	@echo ... src/utilities/UUID_Generator.obj
	@echo ... src/utilities/UUID_Generator.i
	@echo ... src/utilities/UUID_Generator.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

